# Generated by Django 3.2.2 on 2021-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ad_title',
            field=models.CharField(max_length=12),
        ),
    ]
