# Generated by Django 3.2.2 on 2021-06-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ad_title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.CharField(max_length=2000),
        ),
    ]
