# Generated by Django 3.2.2 on 2021-06-29 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210629_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
