# Generated by Django 3.2.2 on 2021-06-30 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
